### ISSUE TITLE
GPU requirement

### ISSUE THREAD

**Issue by nahidalam** [jmiemirza/MMFM-Challenge#1]
Do you have any recommendation on GPU requirement? What type of NVIDIA GPU and what should be the minimum GPU memory requirement?

**Comment by jmiemirza** [comment]
Hi,

The type/amount of GPUs depends on the model you are trying to train. The baselines present in our README were trained on a single node with 8 NVIDIA A100 GPUs. 

For participation in the challenge, there is no limit to the amount/type of GPUs which can be used.
