### ISSUE TITLE
Error running instruction tuning data mix

### ISSUE THREAD

**Issue by nahidalam** [jmiemirza/MMFM-Challenge#2]
For creating the data mix as mentioned [here](https://github.com/nahidalam/MMFM-Challenge/blob/master/docs/training.md)

When I run 
```
python build_train_data.py \
--output_path ./data/data_mix.json \
--train_file_name converted_output_train.json \
--sub_ds_list docvqa,infographicvqa,websrc,wtq,iconqa_fill_in_blank,funsd,iconqa_choose_txt,wildreceipt,textbookqa,tabfact \
--data_path data/processed_data \
--mixin lib/LLaVA/data/llava_v1_5_mix665k.json
```

I get error with the tabfact dataset `OSError: [Errno 40] Too many levels of symbolic links: 'lib/LLaVA/data/llava_v1_5_mix665k.json'`. After I solve this symbolic link error, I get a new error `FileNotFoundError: [Errno 2] No such file or directory: 'lib/LLaVA/data/llava_v1_5_mix665k.json'` . Indeed there is no directory called `lib/LLaVA/data/`

**Steps to reproduce:**

1. Per your [installation instruction](https://github.com/nahidalam/MMFM-Challenge/blob/master/docs/installation.md) - I create symbolic link using `ln -s LLaVA MMFM-Challenge/lib/LLaVA`. After this and finishing all other installation instruction, if I do `python build_train_data.py ...` I get below error

```
docvqa: 0it [00:00, ?it/s]
infographicvqa: 0it [00:00, ?it/s]
websrc: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 307315/307315 [00:00<00:00, 768920.25it/s]
wtq: 0it [00:00, ?it/s]
iconqa_fill_in_blank: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10913/10913 [00:00<00:00, 809515.58it/s]
funsd: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6621/6621 [00:00<00:00, 748813.21it/s]
iconqa_choose_txt: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18946/18946 [00:00<00:00, 775324.01it/s]
wildreceipt: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41119/41119 [00:00<00:00, 753671.16it/s]
textbookqa: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6501/6501 [00:00<00:00, 760654.18it/s]
tabfact: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/MMFM-Challenge/build_train_data.py", line 56, in <module>
    main()
  File "/home/ubuntu/MMFM-Challenge/build_train_data.py", line 48, in main
    with open(args.mixin, 'r') as f:
OSError: [Errno 40] Too many levels of symbolic links: 'lib/LLaVA/data/llava_v1_5_mix665k.json'
```

2. I think when you created the symlink with the `LLaVA` directory using this command `ln -s LLaVA MMFM-Challenge/lib/LLaVA` this got issues. Based on this [article](https://www.baeldung.com/linux/too-many-levels-of-symlinks), we need to specify absolute path for the source here 

So I fix this with `ln -s /home/ubuntu/LLaVA MMFM-Challenge/lib/LLaVA` that solves that symbolic link issue. But now I am getting a new error

```
docvqa: 0it [00:00, ?it/s]
infographicvqa: 0it [00:00, ?it/s]
websrc: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 307315/307315 [00:00<00:00, 773880.20it/s]
wtq: 0it [00:00, ?it/s]
iconqa_fill_in_blank: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10913/10913 [00:00<00:00, 805923.75it/s]
funsd: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6621/6621 [00:00<00:00, 767331.29it/s]
iconqa_choose_txt: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18946/18946 [00:00<00:00, 794366.86it/s]
wildreceipt: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41119/41119 [00:00<00:00, 755751.81it/s]
textbookqa: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6501/6501 [00:00<00:00, 787840.81it/s]
tabfact: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/MMFM-Challenge/build_train_data.py", line 56, in <module>
    main()
  File "/home/ubuntu/MMFM-Challenge/build_train_data.py", line 48, in main
    with open(args.mixin, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'lib/LLaVA/data/llava_v1_5_mix665k.json'
```
 Indeed there is no directory called `lib/LLaVA/data/`

Please suggest.

**Comment by wlin-at** [comment]
> For creating the data mix as mentioned [here](https://github.com/nahidalam/MMFM-Challenge/blob/master/docs/training.md)
> 
> When I run
> 
> ```
> python build_train_data.py \
> --output_path ./data/data_mix.json \
> --train_file_name converted_output_train.json \
> --sub_ds_list docvqa,infographicvqa,websrc,wtq,iconqa_fill_in_blank,funsd,iconqa_choose_txt,wildreceipt,textbookqa,tabfact \
> --data_path data/processed_data \
> --mixin lib/LLaVA/data/llava_v1_5_mix665k.json
> ```
> 
> I get error with the tabfact dataset `OSError: [Errno 40] Too many levels of symbolic links: 'lib/LLaVA/data/llava_v1_5_mix665k.json'`. After I solve this symbolic link error, I get a new error `FileNotFoundError: [Errno 2] No such file or directory: 'lib/LLaVA/data/llava_v1_5_mix665k.json'` . Indeed there is no directory called `lib/LLaVA/data/`
> 
> **Steps to reproduce:**
> 
>     1. Per your [installation instruction](https://github.com/nahidalam/MMFM-Challenge/blob/master/docs/installation.md) - I create symbolic link using `ln -s LLaVA MMFM-Challenge/lib/LLaVA`. After this and finishing all other installation instruction, if I do `python build_train_data.py ...` I get below error
> 
> 
> ```
> docvqa: 0it [00:00, ?it/s]
> infographicvqa: 0it [00:00, ?it/s]
> websrc: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 307315/307315 [00:00<00:00, 768920.25it/s]
> wtq: 0it [00:00, ?it/s]
> iconqa_fill_in_blank: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10913/10913 [00:00<00:00, 809515.58it/s]
> funsd: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6621/6621 [00:00<00:00, 748813.21it/s]
> iconqa_choose_txt: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18946/18946 [00:00<00:00, 775324.01it/s]
> wildreceipt: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41119/41119 [00:00<00:00, 753671.16it/s]
> textbookqa: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6501/6501 [00:00<00:00, 760654.18it/s]
> tabfact: 0it [00:00, ?it/s]
> Traceback (most recent call last):
>   File "/home/ubuntu/MMFM-Challenge/build_train_data.py", line 56, in <module>
>     main()
>   File "/home/ubuntu/MMFM-Challenge/build_train_data.py", line 48, in main
>     with open(args.mixin, 'r') as f:
> OSError: [Errno 40] Too many levels of symbolic links: 'lib/LLaVA/data/llava_v1_5_mix665k.json'
> ```
> 
>     2. I think when you created the symlink with the `LLaVA` directory using this command `ln -s LLaVA MMFM-Challenge/lib/LLaVA` this got issues. Based on this [article](https://www.baeldung.com/linux/too-many-levels-of-symlinks), we need to specify absolute path for the source here
> 
> 
> So I fix this with `ln -s /home/ubuntu/LLaVA MMFM-Challenge/lib/LLaVA` that solves that symbolic link issue. But now I am getting a new error
> 
> ```
> docvqa: 0it [00:00, ?it/s]
> infographicvqa: 0it [00:00, ?it/s]
> websrc: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 307315/307315 [00:00<00:00, 773880.20it/s]
> wtq: 0it [00:00, ?it/s]
> iconqa_fill_in_blank: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10913/10913 [00:00<00:00, 805923.75it/s]
> funsd: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6621/6621 [00:00<00:00, 767331.29it/s]
> iconqa_choose_txt: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18946/18946 [00:00<00:00, 794366.86it/s]
> wildreceipt: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41119/41119 [00:00<00:00, 755751.81it/s]
> textbookqa: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6501/6501 [00:00<00:00, 787840.81it/s]
> tabfact: 0it [00:00, ?it/s]
> Traceback (most recent call last):
>   File "/home/ubuntu/MMFM-Challenge/build_train_data.py", line 56, in <module>
>     main()
>   File "/home/ubuntu/MMFM-Challenge/build_train_data.py", line 48, in main
>     with open(args.mixin, 'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'lib/LLaVA/data/llava_v1_5_mix665k.json'
> ```
> 
> Indeed there is no directory called `lib/LLaVA/data/`
> 
> Please suggest.

Hi nahidalam,

thanks for the pointing out the issues!
1. We updated the [installation instruction](https://github.com/jmiemirza/MMFM-Challenge/blob/master/docs/installation.md) for symbolic link generation according to your feedback. 
2. We added the instructions for preparing the LLaVA instruction tuning data in the [training instruction](https://github.com/jmiemirza/MMFM-Challenge/blob/master/docs/training.md)

the MMFM-Challenge team

**Comment by nahidalam** [comment]
Thanks, that works
